spring.application.name=Back-End

apisix.default.host=http://127.0.0.1
apisix.default.control-port=9882
apisix.default.metrics-port=9881

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8081/realms/frank
spring.security.oauth2.client.registration.keycloak.client-id=frank-confidential
spring.security.oauth2.client.registration.keycloak.client-secret=frank-confidential-secret
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,roles
